version: "3"

services:
  web:
    build: ./docker/web/
    ports:
        - "80:80"
    volumes:
        - .:/var/www/html
    networks:
        - db
    depends_on:
        - db

  db:
    image: mysql:5.7
    volumes:
        - data-volume:/var/lib/mysql
    ports:
        - 3606:3606
    environment:
          MYSQL_ROOT_PASSWORD: root_pwd
          MYSQL_DATABASE: db_test
          MYSQL_USER: db_user
          MYSQL_PASSWORD: db_pwd
    networks:
        - db

volumes:
  data-volume:

networks:
  db:
